name: 'LinkedIn Marketing Workflow'
author: 'Leo Smith - p4p1'
description: 'Send a linkedin post on rss feed update'

inputs:
  rss_feed:
    description: 'rss feed link'
    required: true
  LINKEDIN_SECRET:
    description: 'LinkedIn token for API requests'
    required: true

runs:
  using: node16
  main: dist/index.js
branding:
  icon: 'align-center'
  color: 'blue'
