name: 'LinkedIn Marketing Workflow'
author: 'Leo Smith - p4p1'
description: 'Send a linkedin post on rss feed update'

inputs:
  rss_feed:
    description: 'rss feed linke'
    required: true
  LINKEDIN_TOKEN:
    description: 'Linkedin token'
    required: true

runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'cloud-lightning'
  color: 'red'
