name: Linkedin Marketing Workflow

on:
  schedule:
    - cron: '0 0 * * *'
    workflow_dispatch:
jobs:
  linkedin-marketing-workflow:
    name: Does a linked in post using your rss feed
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      with:
        rss_feed: "https://leosmith.xyz/rss/blog.xml"
        LINKEDIN_TOKEN: ${{secrets.LINKEDIN_TOKEN}}
